import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ar' | 'en';
type Module = 'admin' | 'entity';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  module: Module;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Module, Record<Language, Record<string, string>>> = {
  admin: {
    ar: {
      // Header & Navigation
      'app.title': 'إدارة المحتوى',
      'nav.contentManagement': 'إدارة المحتوى',
      'nav.faq': 'الأسئلة الشائعة',
      'nav.dataSources': 'مصادر البيانات',
      'nav.queries': 'الاستعلامات',
      'nav.analytics': 'التحليلات',
      'nav.settings': 'الإعدادات',
      'nav.documentation': 'التوثيق',
      'nav.support': 'الدعم',
      
      // Content Management List
      'content.title': 'إدارة المحتوى',
      'content.subtitle': 'إدارة المحتوى المتاح للجهات',
      'content.addContent': 'إضافة محتوى',
      'content.tabs.active': 'المحتوى النشط',
      'content.tabs.archived': 'المحتوى المؤرشف',
      'content.search.placeholder': 'ابحث عن محتوى',
      'content.filter.contentType': 'نوع المحتوى',
      'content.filter.entityType': 'نوع الجهة',
      'content.filter.branch': 'الفرع',
      'content.filter.status': 'حالة النشر',
      'content.filter.dateRange': 'نطاق التاريخ',
      'content.filter.all': 'الكل',
      'content.filter.guide': 'دليل',
      'content.filter.assessment': 'تقييم',
      'content.filter.published': 'منشور',
      'content.filter.draft': 'مسودة',
      'content.filter.apply': 'تطبيق',
      'content.filter.reset': 'إعادة تعيين',
      
      // Table Headers
      'table.contentName': 'اسم المحتوى',
      'table.contentType': 'نوع المحتوى',
      'table.branch': 'الفرع',
      'table.targetEntity': 'الجهة المستهدفة',
      'table.publishStatus': 'حالة النشر',
      'table.lastUpdate': 'آخر تحديث',
      'table.actions': 'الإجراءات',
      'table.view': 'عرض',
      'table.edit': 'تعديل',
      'table.delete': 'حذف',
      
      // FAQ Management
      'faq.title': 'إدارة الأسئلة الشائعة',
      'faq.subtitle': 'إدارة الأسئلة الشائعة للجهات',
      'faq.addFAQ': 'إضافة سؤال',
      'faq.tabs.all': 'الكل',
      'faq.tabs.published': 'منشور',
      'faq.tabs.notPublished': 'غير منشور',
      'faq.question': 'السؤال',
      'faq.answer': 'الإجابة',
      'faq.category': 'التصنيف',
      'faq.tags': 'الوسوم',
      'faq.enablePublishing': 'تفعيل النشر',
      'faq.disablePublishing': 'إيقاف النشر',
      'faq.save': 'حفظ',
      'faq.cancel': 'إلغاء',
      
      // Common
      'common.back': 'رجوع',
      'common.save': 'حفظ',
      'common.cancel': 'إلغاء',
      'common.delete': 'حذف',
      'common.edit': 'تعديل',
      'common.view': 'عرض',
      'common.search': 'بحث',
      'common.filter': 'فلترة',
      'common.export': 'تصدير',
      'common.import': 'استيراد',
      'common.loading': 'جاري التحميل...',
      'common.noData': 'لا توجد بيانات',
      'common.success': 'نجح',
      'common.error': 'خطأ',
      'common.switchToEntity': 'التبديل إلى واجهة المستخدم',
      'common.switchToAdmin': 'التبديل إلى واجهة المسؤول',
      'content_added_successfully': 'تمت إضافة المحتوى بنجاح',
      'switch_to_admin_view': 'التبديل إلى واجهة المسؤول',
      'switch_to_entity_view': 'التبديل إلى واجهة الجة',
      
      // Pagination
      'pagination.showing': 'عرض',
      'pagination.to': 'إلى',
      'pagination.of': 'من',
      'pagination.results': 'نتيجة',
      'pagination.previous': 'السابق',
      'pagination.next': 'التالي',
      
      // Data Sources
      'dataSources.title': 'مصادر البيانات',
      'dataSources.subtitle': '',
      'dataSources.headerSubtitle': 'إدارة وتكوين مصادر البيانات الخارجية',
      'dataSources.search': 'البحث عن مصدر بيانات...',
      'dataSources.add': 'إضافة مصدر بيانات جديد',
      'dataSources.systemName': 'اسم مصدر البيانات',
      'dataSources.businessDomain': 'مجال الأعمال',
      'dataSources.apiVersion': 'إصدار API',
      'dataSources.endpointsCount': 'عدد النقاط الطرفية',
      'dataSources.status': 'الحالة',
      'dataSources.actions': 'الإجراءات',
      'dataSources.active': 'نشط',
      'dataSources.inactive': 'غير نشط',
      'dataSources.manageEndpoints': 'إدارة النقاط الطرفية',
      'dataSources.viewDetails': 'عرض',
      'dataSources.edit': 'تعديل',
      'dataSources.deactivate': 'تعطيل',
      'dataSources.activate': 'تفعيل',
      'dataSources.pagination.showing': 'عرض',
      'dataSources.pagination.to': 'إلى',
      'dataSources.pagination.of': 'من',
      'dataSources.pagination.results': 'نتيجة',
      'dataSources.pagination.previous': 'السابق',
      'dataSources.pagination.next': 'التالي',
      'dataSources.empty.title': 'لا توجد بيانات',
      'dataSources.empty.description': '',
      'addDataSource.step1': 'تفاصيل مصدر البيانات',
      'addDataSource.step2': 'تكوين النقاط النهائية',
      'addDataSource.back': 'السابق',

      // Queries
      'queries.title': 'الاستعلامات',
      'queries.subtitle': 'إدارة وإنشاء الاستعلامات على مصادر البيانات',
      'queries.headerSubtitle': 'إدارة وإنشاء الاستعلامات على مصادر البيانات',
      'queries.search': 'البحث عن استعلام...',
      'queries.create': 'إنشاء استعلام',
      'queries.queryName': 'اسم الاستعلام',
      'queries.dataSource': 'مصدر البيانات',
      'queries.endpoint': 'النقطة الطرفية',
      'queries.method': 'الطريقة',
      'queries.status': 'الحالة',
      'queries.actions': 'الإجراءات',
      'queries.active': 'مفعّل',
      'queries.inactive': 'غير نشط',
      'queries.edit': 'تعديل',
      'queries.delete': 'حذف',
      'queries.test': 'اختبار',
      'queries.empty.title': 'لا توجد استعلامات',
      'queries.empty.description': 'ابدأ بإنشاء استعلام جديد للوصول إلى البيانات من مصادر البيانات',
      
      // Query Management
      'queries.listTitle': 'قائمة الاستعلامات',
      'queries.listSubtitle': '',
      'queries.createButton': 'إنشاء استعلام',
      'queries.searchPlaceholder': 'البحث برقم الاستعلام أو العنصر المرتبط',
      'queries.queryId': 'رقم الاستعلام',
      'queries.linkedItem': 'السؤال/المخاطر المرتبط',
      'queries.businessDomain': 'المجال التجاري',
      'queries.lastUpdated': 'آخر تحديث',
      'queries.draft': 'مسودة',
      'queries.disabled': 'معطّل',
      'queries.view': 'عرض',
      'queries.activate': 'تفعيل',
      'queries.deactivate': 'تعطيل',
      'queries.noQueries': 'لا توجد بيانات',
      'queries.noQueriesDescription': '',
      'queries.viewQueryDetails': 'عرض تفاصيل الاستعلام',
      'queries.editQueryDetails': 'تعديل تفاصيل الاستعلام',
      'queries.activateQuery': 'تفعيل الاستعلام',
      'queries.deactivateQuery': 'تعطيل الاستعلام',
      'queries.navigateToLinkedItem': 'الانتقال إلى العنصر المرتبط',
      
      // Query Details
      'queries.detailsTitle': 'تفاصيل الاستعلام',
      'queries.description': 'الوصف',
      'queries.createdAt': 'تاريخ الإنشاء',
      'queries.lastExecution': 'آخر تنفيذ',
      'queries.rulesSection': 'قواعد الاستعلام',
      'queries.field': 'الحقل',
      'queries.operator': 'المعامل',
      'queries.value': 'القيمة',
      'queries.editQuery': 'تعديل الاستعلام',
      'queries.runQuery': 'تشغيل الاستعلام',
      
      // Query Preview/Execution
      'queries.previewTitle': 'معاينة الاستعلام',
      'queries.previewSubtitle': 'تشغيل الاستعلام على البيانات الحالية لمراجعة النتائج',
      'queries.executeQuery': 'تشغيل الاستعلام',
      'queries.entity': 'الكيان',
      'queries.result': 'النتيجة',
      'queries.pass': 'نجاح',
      'queries.fail': 'فشل',
      'queries.noResults': 'لا توجد نتائج',
      'queries.noResultsMessage': 'لم يتم العثور على نتائج لهذا الاستعلام',
      
      // Query History
      'queries.historyTitle': 'سجل تنفيذ الاستعلامات',
      'queries.date': 'التاريخ',
      'queries.resultsCount': 'عدد النتائج',
      'queries.success': 'نجاح',
      'queries.viewResults': 'عرض النتائج',
      
      // Execution Results
      'queries.executionResultsTitle': 'تفاصيل نتائج التنفيذ',
      'queries.source': 'المصدر',
      'queries.filterBySource': 'تصفية حسب المصدر',
      'queries.allSources': 'جميع المصادر',
      
      // Query Form
      'queries.form.queryInfo': 'معلومات الاستعلام',
      'queries.form.queryName': 'اسم الاستعلام',
      'queries.form.queryNameLabel': 'اسم الاستعلام',
      'queries.form.queryNamePlaceholder': 'أدخل اسم الاستعلام',
      'queries.form.status': 'الحالة',
      'queries.form.statusLabel': 'الحالة',
      'queries.form.description': 'الوصف',
      'queries.form.descriptionLabel': 'الوصف',
      'queries.form.descriptionPlaceholder': 'أدخل وصف الاستعلام',
      'queries.form.queryRules': 'قواعد الاستعلام',
      'queries.form.rulesTitle': 'قواعد الاستعلام',
      'queries.form.rulesDescription': 'أضف شروط متعددة لتحديد منطق الاستعلام',
      'queries.form.addCondition': 'إضافة شرط',
      'queries.form.dataSourcePlaceholder': 'مصدر البيانات',
      'queries.form.fieldPlaceholder': 'الحقل',
      'queries.form.operatorPlaceholder': 'المعامل',
      'queries.form.valuePlaceholder': 'القيمة',
      'queries.form.cancel': 'إلغاء',
      'queries.form.saveQuery': 'حفظ الاستعلام',
      'queries.form.saveAndActivate': 'حفظ وتفعيل',
      'queries.form.saveActivate': 'حفظ وتفعيل',
      
      // Success Messages
      'queries.success.saved': 'تم حفظ الاستعلام بنجاح',
      'queries.success.activated': 'تم تفعيل الاستعلام',
      'queries.success.executed': 'تم تشغيل الاستعلام بنجاح',

      // Question Automation
      'questionAutomation.title': 'إدارة الأسئلة المؤتمتة',
      'questionAutomation.tab.questionBank': 'بنك الأسئلة',
      'questionAutomation.searchPlaceholder': 'النص المدخل',
      'questionAutomation.searchButton': 'بحث',
      'questionAutomation.filter': 'تصفية',
      'questionAutomation.entriesInTable': 'عدد الإدخالات في الجدول',
      'questionAutomation.questionId': 'رقم السؤال',
      'questionAutomation.questionText': 'نص السؤال',
      'questionAutomation.questionTitle': 'عنوان السؤال',
      'questionAutomation.dateAdded': 'تاريخ الإضافة',
      'questionAutomation.createdBy': 'أنشئ بواسطة',
      'questionAutomation.dataSource': 'مصدر البيانات',
      'questionAutomation.automationType': 'نوع الأتمتة',
      'questionAutomation.action': 'الإجراء',
      'questionAutomation.activateAutoReplies': 'تفعيل الردود الآلية',
      'questionAutomation.answerType': 'نوع الإجابة',
      'questionAutomation.automationStatus': 'حالة الأتمتة',
      'questionAutomation.businessDomain': 'المجال التجاري',
      'questionAutomation.actions': 'الإجراءات',
      'questionAutomation.type.manual': 'يدوي',
      'questionAutomation.type.auto': 'آلي',
      'questionAutomation.status.manual': 'يدوي',
      'questionAutomation.status.automated': 'مؤتمت',
      'questionAutomation.status.pending': 'قيد المعالجة',
      'questionAutomation.configureAutomation': 'تكوين الأتمتة',
      'questionAutomation.viewQuery': 'عرض الاستعلام',
      'questionAutomation.editQuery': 'تعديل الاستعلام',
      'questionAutomation.deactivate': 'تعطيل',
      'questionAutomation.noData': 'لا توجد بيانات',

      // Configure Automation
      'configureAutomation.title': 'تكوين الأتمتة',
      'configureAutomation.back': 'رجوع للأسئلة',
      'configureAutomation.saveAll': 'حفظ التغييرات',
      'configureAutomation.questionDetails': 'تفاصيل السؤال',
      'configureAutomation.queryBuilder': 'منشئ الاستعلام',
      'configureAutomation.metadataElements': 'عناصر البيانات الوصفية',
      'configureAutomation.queryWorkspace': 'مساحة عمل الاستعلام',
      'configureAutomation.queryStatus': 'حالة الاستعلام',
      'configureAutomation.addCondition': 'إضافة شرط',
      'configureAutomation.selectElement': 'اختر العنصر',
      'configureAutomation.selectOperator': 'اختر المعامل',
      'configureAutomation.enterValue': 'أدخل القيمة',
      'configureAutomation.validateExecute': 'التحقق والتنفيذ',
      'configureAutomation.save': 'حفظ',
      'configureAutomation.cancel': 'إلغاء',
      'configureAutomation.status.automated': 'مؤتمت',
      'configureAutomation.status.unvalidated': 'غير محقق',
      'configureAutomation.status.valid': 'صالح',
      'configureAutomation.status.saved': 'محفوظ',
      'configureAutomation.noConditions': 'لا توجد شروط بعد',
      'configureAutomation.noConditionsHint': 'أضف شرطًا من عناصر البيانات أو ابدأ من الصفر.',
      'configureAutomation.tree.title': 'هيكل الأسئلة',
      'configureAutomation.tree.auto': 'آلي',
      'configureAutomation.tree.autoLegend': 'السؤال مُؤتمت',
      'configureAutomation.sections.question': 'السؤال',
      'configureAutomation.sections.answers': 'الإجابات المحددة مسبقًا',
      'configureAutomation.sections.autoQuery': 'إعدادات الاستعلام الآلي',
      'configureAutomation.predefinedAnswers': 'الإجابات المحددة مسبقًا',
      'configureAutomation.answers.readOnly': 'للقراءة فقط',
      'configureAutomation.answers.helper': 'تُدار الإجابات ضمن بنك الأسئلة ولا يمكن تعديلها هنا. مهمتك هي تكوين الاستعلام الذي سيختار تلقائيًا الإجابة المناسبة.',
      'configureAutomation.weight': 'الوزن',
      'configureAutomation.autoQuery.helper': 'عرّف الاستعلام الذي ينبغي أن يتحقق، ثم اختر الإجابة التي ستُعاد عند تحقق الشروط.',
      'configureAutomation.autoQuery.whenLabel': 'عندما يتحقق الاستعلام التالي',
      'configureAutomation.autoQuery.thenLabel': 'اختَر الإجابة',
      'configureAutomation.autoQuery.answerWith': 'أجِب بـ',
      'configureAutomation.autoQuery.selectAnswer': 'اختر إجابة...',
      'configureAutomation.operator': 'المُعامل',
      'configureAutomation.enabled': 'مُفعّل',
      'configureAutomation.disabled': 'مُعطّل',
      'configureAutomation.status.invalid': 'غير صالح',
      'configureAutomation.automationOff': 'الأتمتة غير مُفعّلة',
      'configureAutomation.automationOffHint': 'فعّل الأتمتة لتكوين استعلام ديناميكي يجيب على هذا السؤال تلقائيًا.',

      // User Groups
      'userGroups.eyebrow': 'التحكم في الوصول',
      'userGroups.title': 'مجموعات المستخدمين',
      'userGroups.subtitle': 'أنشئ مجموعات وربط الأدوار التنظيمية بأدوار إدارة الهوية.',
      'userGroups.createNew': 'إنشاء مجموعة',
      'userGroups.tabs.all': 'الكل',
      'userGroups.tabs.active': 'نشطة',
      'userGroups.tabs.draft': 'مسودة',
      'userGroups.searchPlaceholder': 'ابحث بالاسم أو الوصف',
      'userGroups.filter': 'تصفية',
      'userGroups.groupBadge': 'مجموعة',
      'userGroups.coverage': 'التغطية',
      'userGroups.roles': 'أدوار',
      'userGroups.updated': 'آخر تحديث',
      'userGroups.status.active': 'نشطة',
      'userGroups.status.draft': 'مسودة',
      'userGroups.action.edit': 'تعديل',
      'userGroups.action.duplicate': 'نسخ',
      'userGroups.action.more': 'المزيد',
      'userGroups.empty.title': 'لا توجد مجموعات بعد',
      'userGroups.empty.description': 'ابدأ بإنشاء مجموعة لربط الأدوار التنظيمية بأدوار إدارة الهوية.',
      'userGroups.createFirst': 'إنشاء أول مجموعة',
      'userGroups.saveAll': 'حفظ جميع المجموعات',
      'userGroups.pageHelper': 'أنشئ مجموعات متعددة واربط كل دور تنظيمي بدور مقابل في نظام إدارة الهوية.',
      'userGroups.groupName': 'اسم المجموعة',
      'userGroups.groupNamePlaceholder': 'مثال: فريق الالتزام',
      'userGroups.selectIdm': 'اختر دور IDM…',
      'userGroups.deleteGroup': 'حذف المجموعة',
      'userGroups.expand': 'توسيع',
      'userGroups.collapse': 'طيّ',
      'userGroupEdit.back': 'رجوع إلى المجموعات',
      'userGroupEdit.eyebrowNew': 'مجموعة جديدة',
      'userGroupEdit.eyebrowEdit': 'تعديل المجموعة',
      'userGroupEdit.titleNew': 'إنشاء مجموعة مستخدمين',
      'userGroupEdit.untitled': 'مجموعة بلا عنوان',
      'userGroupEdit.cancel': 'إلغاء',
      'userGroupEdit.save': 'حفظ المجموعة',
      'userGroupEdit.sections.details': 'تفاصيل المجموعة',
      'userGroupEdit.sections.mapping': 'ربط الأدوار',
      'userGroupEdit.sections.activation': 'التفعيل',
      'userGroupEdit.icon': 'الأيقونة',
      'userGroupEdit.name': 'اسم المجموعة',
      'userGroupEdit.namePlaceholder': 'مثال: فريق الالتزام',
      'userGroupEdit.description': 'الوصف',
      'userGroupEdit.descriptionPlaceholder': 'ماذا تمثّل هذه المجموعة؟',
      'userGroupEdit.mappingProgress': 'تقدّم الربط',
      'userGroupEdit.allMapped': 'تم ربط جميع الأدوار',
      'userGroupEdit.remaining': '{n} دور متبقٍّ',
      'userGroupEdit.mappingHelper': 'اربط كل دور تنظيمي بدور مقابل في نظام إدارة الهوية (IDM).',
      'userGroupEdit.importTemplate': 'استيراد من قالب',
      'userGroupEdit.selectIdm': 'اختر دور IDM…',
      'userGroupEdit.activateGroup': 'تفعيل المجموعة',
      'userGroupEdit.activeHint': 'المجموعة مرئية وقابلة للاستخدام.',
      'userGroupEdit.draftHint': 'المجموعة في وضع المسوّدة ولن تظهر للمستخدمين.',
      'userGroupEdit.active': 'نشطة',
      'userGroupEdit.draft': 'مسودة',
      'userGroupEdit.previewIcon': 'أيقونة المجموعة المختارة',

      // Defined Risks
      'definedRisks.title': 'المخاطر المُحدَّدة',
      'definedRisks.subtitle': 'إدارة المخاطر المُحدَّدة وتكوين تحديد الكيانات المُتأثِّرة.',
      'definedRisks.tabs.all': 'الكل',
      'definedRisks.tabs.automated': 'مؤتمت',
      'definedRisks.tabs.manual': 'يدوي',
      'definedRisks.searchPlaceholder': 'ابحث برقم المخاطر أو اسمها',
      'definedRisks.searchButton': 'بحث',
      'definedRisks.filter': 'تصفية',
      'definedRisks.entriesInTable': 'عدد الإدخالات في الجدول',
      'definedRisks.riskId': 'رقم المخاطر',
      'definedRisks.riskName': 'اسم المخاطر',
      'definedRisks.riskLevel': 'مستوى الخطر',
      'definedRisks.businessDomain': 'المجال التجاري',
      'definedRisks.determination': 'طريقة التحديد',
      'definedRisks.dateAdded': 'تاريخ الإضافة',
      'definedRisks.action': 'الإجراء',
      'definedRisks.manual': 'يدوي',
      'definedRisks.autoActive': 'آلي - نشط',
      'definedRisks.autoInactive': 'آلي - مُعطَّل',
      'definedRisks.activateAutomation': 'تفعيل الأتمتة',
      'definedRisks.manageAutomation': 'إدارة الأتمتة',
      'definedRisks.level.critical': 'حرج',
      'definedRisks.level.high': 'مرتفع',
      'definedRisks.level.medium': 'متوسط',
      'definedRisks.level.low': 'منخفض',

      // Queries Admin
      'queriesAdmin.title': 'إدارة الاستعلامات الآلية',
      'queriesAdmin.subtitle': 'راقب وأدِر جميع الاستعلامات الآلية المُكوَّنة في النظام.',
      'queriesAdmin.tabs.all': 'كل الاستعلامات',
      'queriesAdmin.tabs.question': 'أسئلة مؤتمتة',
      'queriesAdmin.tabs.risk': 'مخاطر مُحدَّدة',
      'queriesAdmin.searchPlaceholder': 'ابحث برقم الاستعلام أو العنصر المرتبط',
      'queriesAdmin.searchButton': 'بحث',
      'queriesAdmin.filter': 'تصفية',
      'queriesAdmin.entriesInTable': 'عدد الإدخالات في الجدول',
      'queriesAdmin.queryId': 'رقم الاستعلام',
      'queriesAdmin.linkedItem': 'العنصر المرتبط',
      'queriesAdmin.type': 'النوع',
      'queriesAdmin.businessDomain': 'المجال التجاري',
      'queriesAdmin.status': 'الحالة',
      'queriesAdmin.lastUpdated': 'آخر تحديث',
      'queriesAdmin.action': 'الإجراء',
      'queriesAdmin.linkedType.question': 'سؤال',
      'queriesAdmin.linkedType.risk': 'مخاطر',
      'queriesAdmin.statusActive': 'نشط',
      'queriesAdmin.statusInactive': 'مُعطَّل',
      'queriesAdmin.viewDetails': 'عرض التفاصيل',
      'queriesAdmin.editDetails': 'تعديل التفاصيل',
      'queriesAdmin.activate': 'تفعيل',
      'queriesAdmin.deactivate': 'تعطيل',
      'queriesAdmin.navigateToLinkedItem': 'الانتقال إلى العنصر المرتبط',
      'queriesAdmin.empty.title': 'لا توجد استعلامات',
      'queriesAdmin.empty.description': 'ستظهر الاستعلامات هنا عند ربطها بسؤال مؤتمت أو مخاطر مُحدَّدة.',

      // Auto Reply Settings Dialog
      'autoReply.title': 'إعدادات الرد الآلي',
      'autoReply.titleView': 'عرض تفاصيل الاستعلام',
      'autoReply.titleEdit': 'تعديل تفاصيل الاستعلام',
      'autoReply.titleRisk': 'إعدادات أتمتة المخاطر',
      'autoReply.titleViewRisk': 'عرض تفاصيل استعلام المخاطر',
      'autoReply.titleEditRisk': 'تعديل تفاصيل استعلام المخاطر',
      'autoReply.eyebrowRisk': 'أتمتة المخاطر المُحدَّدة',
      'autoReply.risk': 'المخاطر',
      'autoReply.predefinedScoresRange': 'نطاق الدرجات المُحدَّد مسبقًا',
      'autoReply.readOnly': 'للقراءة فقط',
      'autoReply.switchToEdit': 'تعديل',
      'autoReply.close': 'إغلاق',
      'autoReply.footerHintView': 'هذه الاستعلام معروض للقراءة فقط.',
      'autoReply.eyebrow': 'أتمتة السؤال',
      'autoReply.active': 'مُفعَّل',
      'autoReply.inactive': 'مُعطَّل',
      'autoReply.footerHint': 'تُحفظ التغييرات عند الضغط على زر الحفظ.',
      'autoReply.inquiryResultMatched': 'نتيجة الاستعلام · تم المطابقة',
      'autoReply.resolvedIn': 'تم الحل خلال {ms} مللي ثانية',
      'autoReply.editor.emptyTitle': 'ابدأ ببناء استعلامك',
      'autoReply.editor.emptyHint': 'اختر المجال، ثم النظام، ثم العنصر',
      'autoReply.question': 'السؤال',
      'autoReply.subQuestion': 'السؤال الفرعي',
      'autoReply.mainQuestion': '— السؤال الرئيسي —',
      'autoReply.predefinedAnswers': 'الإجابات المحددة مسبقًا',
      'autoReply.activateDeactivate': 'تفعيل / تعطيل',
      'autoReply.answer': 'الإجابة',
      'autoReply.weight': 'الوزن',
      'autoReply.autoQuerySettings': 'إعدادات الاستعلام الآلي',
      'autoReply.tabForInstructions': 'تعليمات الاستخدام',
      'autoReply.checkInquiry': 'تحقق من الاستعلام',
      'autoReply.inquiryResult': 'نتيجة الاستعلام',
      'autoReply.cancel': 'إلغاء',
      'autoReply.save': 'حفظ',
      'autoReply.editor.placeholder': 'استخدم "/" لإدراج عناصر المعادلة',
      'autoReply.editor.if': 'إذا',
      'autoReply.editor.pickDomain': 'اختر المجال',
      'autoReply.editor.pickSource': 'اختر النظام',
      'autoReply.editor.pickElement': 'اختر العنصر',
      'autoReply.editor.pickOperator': 'المُعامل',
      'autoReply.editor.enterValue': 'أدخل القيمة',
      'autoReply.editor.removeCondition': 'حذف الشرط',
      'autoReply.editor.chooseWorkField': 'مجال العمل',
      'autoReply.editor.chooseSystem': 'النظام',
      'autoReply.editor.chooseDescription': 'البيان الوصفي',
      'autoReply.editor.chooseOperator': 'المُعامل',
      'autoReply.editor.search': 'بحث...',
      'autoReply.inquiry.incomplete': 'يرجى إكمال جميع الشروط قبل التحقق.',
      'autoReply.inquiry.noAnswers': 'لا توجد إجابات محددة مسبقًا مرتبطة بهذا السؤال.',
      'autoReply.save.needsQuery': 'يجب تكوين استعلام مكتمل قبل الحفظ.',
    },
    en: {
      // Header & Navigation
      'app.title': 'Content Management',
      'nav.contentManagement': 'Content Management',
      'nav.faq': 'FAQs',
      'nav.dataSources': 'Data Sources',
      'nav.queries': 'Queries',
      'nav.analytics': 'Analytics',
      'nav.settings': 'Settings',
      'nav.documentation': 'Documentation',
      'nav.support': 'Support',
      
      // Content Management List
      'content.title': 'Content Management',
      'content.subtitle': 'Manage available content for entities',
      'content.addContent': 'Add Content',
      'content.tabs.active': 'Active Content',
      'content.tabs.archived': 'Archived Content',
      'content.search.placeholder': 'Search for content',
      'content.filter.contentType': 'Content Type',
      'content.filter.entityType': 'Entity Type',
      'content.filter.branch': 'Branch',
      'content.filter.status': 'Publish Status',
      'content.filter.dateRange': 'Date Range',
      'content.filter.all': 'All',
      'content.filter.guide': 'Guide',
      'content.filter.assessment': 'Assessment',
      'content.filter.published': 'Published',
      'content.filter.draft': 'Draft',
      'content.filter.apply': 'Apply',
      'content.filter.reset': 'Reset',
      
      // Table Headers
      'table.contentName': 'Content Name',
      'table.contentType': 'Content Type',
      'table.branch': 'Branch',
      'table.targetEntity': 'Target Entity',
      'table.publishStatus': 'Publish Status',
      'table.lastUpdate': 'Last Updated',
      'table.actions': 'Actions',
      'table.view': 'View',
      'table.edit': 'Edit',
      'table.delete': 'Delete',
      
      // FAQ Management
      'faq.title': 'FAQ Management',
      'faq.subtitle': 'Manage frequently asked questions for entities',
      'faq.addFAQ': 'Add Question',
      'faq.tabs.all': 'All',
      'faq.tabs.published': 'Published',
      'faq.tabs.notPublished': 'Not Published',
      'faq.question': 'Question',
      'faq.answer': 'Answer',
      'faq.category': 'Category',
      'faq.tags': 'Tags',
      'faq.enablePublishing': 'Enable Publishing',
      'faq.disablePublishing': 'Disable Publishing',
      'faq.save': 'Save',
      'faq.cancel': 'Cancel',
      
      // Common
      'common.back': 'Back',
      'common.save': 'Save',
      'common.cancel': 'Cancel',
      'common.delete': 'Delete',
      'common.edit': 'Edit',
      'common.view': 'View',
      'common.search': 'Search',
      'common.filter': 'Filter',
      'common.export': 'Export',
      'common.import': 'Import',
      'common.loading': 'Loading...',
      'common.noData': 'No Data',
      'common.success': 'Success',
      'common.error': 'Error',
      'common.switchToEntity': 'Switch to User View',
      'common.switchToAdmin': 'Switch to Admin View',
      'content_added_successfully': 'Content added successfully',
      'switch_to_admin_view': 'Switch to Admin View',
      'switch_to_entity_view': 'Switch to Entity View',
      
      // Pagination
      'pagination.showing': 'Showing',
      'pagination.to': 'to',
      'pagination.of': 'of',
      'pagination.results': 'results',
      'pagination.previous': 'Previous',
      'pagination.next': 'Next',
      
      // Data Sources
      'dataSources.title': 'List of Sources',
      'dataSources.subtitle': '',
      'dataSources.headerSubtitle': 'Manage and configure external data sources',
      'dataSources.search': 'Search for data source...',
      'dataSources.add': 'Add New Data Source',
      'dataSources.systemName': 'Data Source Name',
      'dataSources.businessDomain': 'Business Domain',
      'dataSources.apiVersion': 'API Version',
      'dataSources.endpointsCount': 'Endpoints Count',
      'dataSources.status': 'Status',
      'dataSources.actions': 'Actions',
      'dataSources.active': 'Active',
      'dataSources.inactive': 'Inactive',
      'dataSources.manageEndpoints': 'Manage Endpoints',
      'dataSources.viewDetails': 'View',
      'dataSources.edit': 'Edit',
      'dataSources.deactivate': 'Deactivate',
      'dataSources.activate': 'Activate',
      'dataSources.pagination.showing': 'Showing',
      'dataSources.pagination.to': 'to',
      'dataSources.pagination.of': 'of',
      'dataSources.pagination.results': 'results',
      'dataSources.pagination.previous': 'Previous',
      'dataSources.pagination.next': 'Next',
      'dataSources.empty.title': 'No Data',
      'dataSources.empty.description': '',
      'addDataSource.step1': 'Data Source Details',
      'addDataSource.step2': 'Configure Endpoints',
      'addDataSource.back': 'Back',

      // Queries
      'queries.title': 'Queries',
      'queries.subtitle': 'Manage and create queries on data sources',
      'queries.headerSubtitle': 'Manage and create queries on data sources',
      'queries.search': 'Search for a query...',
      'queries.create': 'Create Query',
      'queries.queryName': 'Query Name',
      'queries.dataSource': 'Data Source',
      'queries.endpoint': 'Endpoint',
      'queries.method': 'Method',
      'queries.status': 'Status',
      'queries.actions': 'Actions',
      'queries.active': 'Activated',
      'queries.inactive': 'Inactive',
      'queries.edit': 'Edit',
      'queries.delete': 'Delete',
      'queries.test': 'Test',
      'queries.empty.title': 'No Queries',
      'queries.empty.description': 'Start by creating a new query to access data from data sources',
      
      // Query Management
      'queries.listTitle': 'List of Queries',
      'queries.listSubtitle': '',
      'queries.createButton': 'Create Query',
      'queries.searchPlaceholder': 'Search by Query ID or Linked Item',
      'queries.linkedItem': 'Linked Question/Risk',
      'queries.queryId': 'Query ID',
      'queries.businessDomain': 'Business Domain',
      'queries.lastUpdated': 'Last Updated',
      'queries.draft': '',
      'queries.disabled': 'Deactivated',
      'queries.view': 'View',
      'queries.activate': 'Activate',
      'queries.deactivate': 'Deactivate',
      'queries.noQueries': 'No Data',
      'queries.noQueriesDescription': '',
      'queries.viewQueryDetails': 'View Query Details',
      'queries.editQueryDetails': 'Edit Query Details',
      'queries.activateQuery': 'Activate Query',
      'queries.deactivateQuery': 'Deactivate Query',
      'queries.navigateToLinkedItem': 'Navigate to Linked Item',
      
      // Query Details
      'queries.detailsTitle': 'Query Details',
      'queries.description': 'Description',
      'queries.createdAt': 'Created At',
      'queries.lastExecution': 'Last Execution',
      'queries.rulesSection': 'Query Rules',
      'queries.field': 'Field',
      'queries.operator': 'Operator',
      'queries.value': 'Value',
      'queries.editQuery': 'Edit Query',
      'queries.runQuery': 'Run Query',
      
      // Query Preview/Execution
      'queries.previewTitle': 'Query Preview',
      'queries.previewSubtitle': 'Run the query on current data to review results',
      'queries.executeQuery': 'Execute Query',
      'queries.entity': 'Entity',
      'queries.result': 'Result',
      'queries.pass': 'Pass',
      'queries.fail': 'Fail',
      'queries.noResults': 'No Results',
      'queries.noResultsMessage': 'No results were found for this query',
      
      // Query History
      'queries.historyTitle': 'Query Execution History',
      'queries.date': 'Date',
      'queries.resultsCount': 'Results Count',
      'queries.success': 'Success',
      'queries.viewResults': 'View Results',
      
      // Execution Results
      'queries.executionResultsTitle': 'Execution Results Details',
      'queries.source': 'Source',
      'queries.filterBySource': 'Filter by source',
      'queries.allSources': 'All Sources',
      
      // Query Form
      'queries.form.queryInfo': 'Query Information',
      'queries.form.queryNameLabel': 'Query Name',
      'queries.form.queryNamePlaceholder': 'Enter query name',
      'queries.form.statusLabel': 'Status',
      'queries.form.descriptionLabel': 'Description',
      'queries.form.descriptionPlaceholder': 'Enter query description',
      'queries.form.rulesTitle': 'Query Rules',
      'queries.form.rulesDescription': 'Add multiple conditions to define query logic',
      'queries.form.addCondition': 'Add Condition',
      'queries.form.dataSourcePlaceholder': 'Data Source',
      'queries.form.fieldPlaceholder': 'Field',
      'queries.form.operatorPlaceholder': 'Operator',
      'queries.form.valuePlaceholder': 'Value',
      'queries.form.cancel': 'Cancel',
      'queries.form.saveQuery': 'Save Query',
      'queries.form.saveAndActivate': 'Save & Activate',
      
      // Success Messages
      'queries.success.saved': 'Query saved successfully',
      'queries.success.activated': 'Query activated',
      'queries.success.executed': 'Query executed successfully',

      // Question Automation
      'questionAutomation.title': 'Manage Automated Questions',
      'questionAutomation.tab.questionBank': 'Question Bank',
      'questionAutomation.searchPlaceholder': 'Entered text',
      'questionAutomation.searchButton': 'Search',
      'questionAutomation.filter': 'Filter',
      'questionAutomation.entriesInTable': 'Number of entries in the table',
      'questionAutomation.questionId': 'Question ID',
      'questionAutomation.questionText': 'Question Text',
      'questionAutomation.questionTitle': 'Question Title',
      'questionAutomation.dateAdded': 'Date Added',
      'questionAutomation.createdBy': 'Created By',
      'questionAutomation.dataSource': 'Data Source',
      'questionAutomation.automationType': 'Automation Type',
      'questionAutomation.action': 'Action',
      'questionAutomation.activateAutoReplies': 'Activate Auto Replies',
      'questionAutomation.answerType': 'Answer Type',
      'questionAutomation.automationStatus': 'Automation Status',
      'questionAutomation.businessDomain': 'Business Domain',
      'questionAutomation.actions': 'Actions',
      'questionAutomation.type.manual': 'Manual',
      'questionAutomation.type.auto': 'Auto',
      'questionAutomation.status.manual': 'Manual',
      'questionAutomation.status.automated': 'Automated',
      'questionAutomation.status.pending': 'Pending',
      'questionAutomation.configureAutomation': 'Configure Automation',
      'questionAutomation.viewQuery': 'View Query',
      'questionAutomation.editQuery': 'Edit Query',
      'questionAutomation.deactivate': 'Deactivate',
      'questionAutomation.noData': 'No Data',

      // Configure Automation
      'configureAutomation.title': 'Configure Automation',
      'configureAutomation.back': 'Back to Questions',
      'configureAutomation.saveAll': 'Save Changes',
      'configureAutomation.questionDetails': 'Question Details',
      'configureAutomation.queryBuilder': 'Query Builder',
      'configureAutomation.metadataElements': 'Metadata Elements',
      'configureAutomation.queryWorkspace': 'Query Workspace',
      'configureAutomation.queryStatus': 'Query Status',
      'configureAutomation.addCondition': 'Add Condition',
      'configureAutomation.selectElement': 'Select Element',
      'configureAutomation.selectOperator': 'Select Operator',
      'configureAutomation.enterValue': 'Enter Value',
      'configureAutomation.validateExecute': 'Validate & Execute',
      'configureAutomation.save': 'Save',
      'configureAutomation.cancel': 'Cancel',
      'configureAutomation.status.automated': 'Automated',
      'configureAutomation.status.unvalidated': 'Unvalidated',
      'configureAutomation.status.valid': 'Valid',
      'configureAutomation.status.saved': 'Saved',
      'configureAutomation.noConditions': 'No conditions added yet',
      'configureAutomation.noConditionsHint': 'Click a metadata element on the left or add a blank condition to begin.',
      'configureAutomation.tree.title': 'Question Structure',
      'configureAutomation.tree.auto': 'Auto',
      'configureAutomation.tree.autoLegend': 'Automated question',
      'configureAutomation.sections.question': 'Question',
      'configureAutomation.sections.answers': 'Predefined Answers',
      'configureAutomation.sections.autoQuery': 'Auto Query Settings',
      'configureAutomation.predefinedAnswers': 'Predefined Answers',
      'configureAutomation.answers.readOnly': 'Read only',
      'configureAutomation.answers.helper': 'Answers are managed in the Question Bank and can\u2019t be edited here. Your job is to configure the query that picks the right answer automatically.',
      'configureAutomation.weight': 'Weight',
      'configureAutomation.autoQuery.helper': 'Define when the query should match, then pick which answer to return when it does.',
      'configureAutomation.autoQuery.whenLabel': 'When this query matches',
      'configureAutomation.autoQuery.thenLabel': 'Pick the answer',
      'configureAutomation.autoQuery.answerWith': 'Answer with',
      'configureAutomation.autoQuery.selectAnswer': 'Select an answer\u2026',
      'configureAutomation.operator': 'Operator',
      'configureAutomation.enabled': 'Enabled',
      'configureAutomation.disabled': 'Disabled',
      'configureAutomation.status.invalid': 'Invalid',
      'configureAutomation.automationOff': 'Automation is off',
      'configureAutomation.automationOffHint': 'Enable automation to configure a dynamic query that answers this question automatically.',

      // User Groups
      'userGroups.eyebrow': 'Access Control',
      'userGroups.title': 'User Groups',
      'userGroups.subtitle': 'Create groups and map business roles to Identity Management roles.',
      'userGroups.createNew': 'Create New Group',
      'userGroups.tabs.all': 'All',
      'userGroups.tabs.active': 'Active',
      'userGroups.tabs.draft': 'Draft',
      'userGroups.searchPlaceholder': 'Search by name or description',
      'userGroups.filter': 'Filter',
      'userGroups.groupBadge': 'Group',
      'userGroups.coverage': 'Coverage',
      'userGroups.roles': 'roles',
      'userGroups.updated': 'Updated',
      'userGroups.status.active': 'Active',
      'userGroups.status.draft': 'Draft',
      'userGroups.action.edit': 'Edit',
      'userGroups.action.duplicate': 'Duplicate',
      'userGroups.action.more': 'More',
      'userGroups.empty.title': 'No groups yet',
      'userGroups.empty.description': 'Get started by creating a group that maps business roles to Identity Management roles.',
      'userGroups.createFirst': 'Create your first group',
      'userGroups.saveAll': 'Save All Groups',
      'userGroups.pageHelper': 'Create multiple groups and pair each business role with a role from your Identity Management system.',
      'userGroups.groupName': 'Group Name',
      'userGroups.groupNamePlaceholder': 'e.g. Compliance Team',
      'userGroups.selectIdm': 'Select IDM role\u2026',
      'userGroups.deleteGroup': 'Delete group',
      'userGroups.expand': 'Expand',
      'userGroups.collapse': 'Collapse',
      'userGroupEdit.back': 'Back to Groups',
      'userGroupEdit.eyebrowNew': 'New Group',
      'userGroupEdit.eyebrowEdit': 'Edit Group',
      'userGroupEdit.titleNew': 'Create User Group',
      'userGroupEdit.untitled': 'Untitled Group',
      'userGroupEdit.cancel': 'Cancel',
      'userGroupEdit.save': 'Save Group',
      'userGroupEdit.sections.details': 'Group Details',
      'userGroupEdit.sections.mapping': 'Role Mapping',
      'userGroupEdit.sections.activation': 'Activation',
      'userGroupEdit.icon': 'Icon',
      'userGroupEdit.name': 'Group Name',
      'userGroupEdit.namePlaceholder': 'e.g. Compliance Team',
      'userGroupEdit.description': 'Description',
      'userGroupEdit.descriptionPlaceholder': 'What does this group represent?',
      'userGroupEdit.mappingProgress': 'Mapping Progress',
      'userGroupEdit.allMapped': 'All roles mapped',
      'userGroupEdit.remaining': '{n} remaining',
      'userGroupEdit.mappingHelper': 'Pair each business role with a role from the Identity Management (IDM) system.',
      'userGroupEdit.importTemplate': 'Import from template',
      'userGroupEdit.selectIdm': 'Select IDM role\u2026',
      'userGroupEdit.activateGroup': 'Activate Group',
      'userGroupEdit.activeHint': 'Group is visible and usable.',
      'userGroupEdit.draftHint': 'Group is in draft mode and hidden from users.',
      'userGroupEdit.active': 'Active',
      'userGroupEdit.draft': 'Draft',
      'userGroupEdit.previewIcon': 'Selected group icon',

      // Defined Risks
      'definedRisks.title': 'Defined Risks',
      'definedRisks.subtitle': 'Manage defined risks and configure how affected entities are determined.',
      'definedRisks.tabs.all': 'All',
      'definedRisks.tabs.automated': 'Automated',
      'definedRisks.tabs.manual': 'Manual',
      'definedRisks.searchPlaceholder': 'Search by Risk ID or name',
      'definedRisks.searchButton': 'Search',
      'definedRisks.filter': 'Filter',
      'definedRisks.entriesInTable': 'Number of entries in the table',
      'definedRisks.riskId': 'Risk ID',
      'definedRisks.riskName': 'Risk Name',
      'definedRisks.riskLevel': 'Risk Level',
      'definedRisks.businessDomain': 'Business Domain',
      'definedRisks.determination': 'Determination',
      'definedRisks.dateAdded': 'Date Added',
      'definedRisks.action': 'Action',
      'definedRisks.manual': 'Manual',
      'definedRisks.autoActive': 'Auto · Active',
      'definedRisks.autoInactive': 'Auto · Inactive',
      'definedRisks.activateAutomation': 'Activate Automation',
      'definedRisks.manageAutomation': 'Manage Automation',
      'definedRisks.level.critical': 'Critical',
      'definedRisks.level.high': 'High',
      'definedRisks.level.medium': 'Medium',
      'definedRisks.level.low': 'Low',

      // Queries Admin
      'queriesAdmin.title': 'Manage Automated Queries',
      'queriesAdmin.subtitle': 'Monitor and manage every automated query configured in the system.',
      'queriesAdmin.tabs.all': 'All Queries',
      'queriesAdmin.tabs.question': 'Automated Questions',
      'queriesAdmin.tabs.risk': 'Defined Risks',
      'queriesAdmin.searchPlaceholder': 'Search by Query ID or linked item',
      'queriesAdmin.searchButton': 'Search',
      'queriesAdmin.filter': 'Filter',
      'queriesAdmin.entriesInTable': 'Number of entries in the table',
      'queriesAdmin.queryId': 'Query ID',
      'queriesAdmin.linkedItem': 'Linked Item',
      'queriesAdmin.type': 'Type',
      'queriesAdmin.businessDomain': 'Business Domain',
      'queriesAdmin.status': 'Status',
      'queriesAdmin.lastUpdated': 'Last Updated',
      'queriesAdmin.action': 'Action',
      'queriesAdmin.linkedType.question': 'Question',
      'queriesAdmin.linkedType.risk': 'Risk',
      'queriesAdmin.statusActive': 'Active',
      'queriesAdmin.statusInactive': 'Inactive',
      'queriesAdmin.viewDetails': 'View Query Details',
      'queriesAdmin.editDetails': 'Edit Query Details',
      'queriesAdmin.activate': 'Activate Query',
      'queriesAdmin.deactivate': 'Deactivate Query',
      'queriesAdmin.navigateToLinkedItem': 'Navigate to Linked Item',
      'queriesAdmin.empty.title': 'No queries yet',
      'queriesAdmin.empty.description': 'Queries will appear here once they are linked to an automated question or defined risk.',

      // Auto Reply Settings Dialog
      'autoReply.title': 'Auto Reply Settings',
      'autoReply.titleView': 'View Query Details',
      'autoReply.titleEdit': 'Edit Query Details',
      'autoReply.titleRisk': 'Risk Automation Settings',
      'autoReply.titleViewRisk': 'View Risk Query Details',
      'autoReply.titleEditRisk': 'Edit Risk Query Details',
      'autoReply.eyebrowRisk': 'Defined Risk Automation',
      'autoReply.risk': 'Risk',
      'autoReply.predefinedScoresRange': 'Predefined Scores Range',
      'autoReply.readOnly': 'Read Only',
      'autoReply.switchToEdit': 'Edit',
      'autoReply.close': 'Close',
      'autoReply.footerHintView': 'This query is currently shown in read-only mode.',
      'autoReply.eyebrow': 'Question Automation',
      'autoReply.active': 'Active',
      'autoReply.inactive': 'Inactive',
      'autoReply.footerHint': 'Changes are saved when you click Save.',
      'autoReply.inquiryResultMatched': 'Inquiry Result \u00B7 Matched',
      'autoReply.resolvedIn': 'Resolved in {ms}ms',
      'autoReply.editor.emptyTitle': 'Start building your query',
      'autoReply.editor.emptyHint': 'Pick a work field, then system, then element',
      'autoReply.question': 'Question',
      'autoReply.subQuestion': 'Sub Question',
      'autoReply.mainQuestion': '\u2014 Main Question \u2014',
      'autoReply.predefinedAnswers': 'Predefined Answers',
      'autoReply.activateDeactivate': 'Activate / Deactivate',
      'autoReply.answer': 'Answer',
      'autoReply.weight': 'Weight',
      'autoReply.autoQuerySettings': 'Auto Query Settings',
      'autoReply.tabForInstructions': 'Tab For Instructions',
      'autoReply.checkInquiry': 'Check Inquiry',
      'autoReply.inquiryResult': 'Inquiry Result',
      'autoReply.cancel': 'Cancel',
      'autoReply.save': 'Save',
      'autoReply.editor.placeholder': 'Use \u201C/\u201D to insert equation elements',
      'autoReply.editor.if': 'If',
      'autoReply.editor.pickDomain': 'Pick work field',
      'autoReply.editor.pickSource': 'Pick system',
      'autoReply.editor.pickElement': 'Pick element',
      'autoReply.editor.pickOperator': 'Operator',
      'autoReply.editor.enterValue': 'Enter value',
      'autoReply.editor.removeCondition': 'Remove condition',
      'autoReply.editor.chooseWorkField': 'Work Field',
      'autoReply.editor.chooseSystem': 'Choose System',
      'autoReply.editor.chooseDescription': 'Choose Description',
      'autoReply.editor.chooseOperator': 'Choose Operator',
      'autoReply.editor.search': 'Search\u2026',
      'autoReply.inquiry.incomplete': 'Please complete all conditions before checking.',
      'autoReply.inquiry.noAnswers': 'No predefined answers are linked to this question.',
      'autoReply.save.needsQuery': 'A complete query is required before saving.',
    }
  },
  entity: {
    ar: {
      // Header
      'app.title': 'قاعدة المعرفة',
      'header.welcome': 'مرحباً بك',
      'header.entityName': 'جهة حكومية - الرياض',
      
      // Navigation
      'nav.knowledgeBase': 'قاعدة المعرفة',
      'nav.calculator': 'الحاسبة المالية',
      'nav.profile': 'الملف الشخصي',
      'nav.notifications': 'الإشعارات',
      'nav.settings': 'الإعدادات',
      
      // Knowledge Base
      'kb.title': 'قاعدة المعرفة',
      'kb.subtitle': 'استعرض المحتوى والموارد المتاحة',
      'kb.tabs.available': 'المحتوى المتاح',
      'kb.tabs.faq': 'الاسئلة الشائعة',
      'kb.tabs.favorites': 'المحتوى المفضل',
      'kb.subTabs.content': 'المحتوى',
      'kb.subTabs.faq': 'الأسئلة الشائعة',
      'kb.search.placeholder': 'ابحث في المحتوى',
      'kb.filter.contentType': 'نوع المحتوى',
      'kb.filter.all': 'الكل',
      'kb.filter.guide': 'دليل',
      'kb.filter.assessment': 'تقييم',
      'kb.noFavorites': 'لا يوجد محتوى مفضل',
      'kb.noFavoritesDesc': 'لم تقم بإضافة أي محتوى إلى المفضلة بعد. ابدأ بتصفح المحتوى المتاح وأضف ما يهمك.',
      'kb.browseContent': 'تصفح المحتوى المتاح',
      'kb.view': 'عرض',
      'kb.publishDate': 'تاريخ النشر',
      'kb.lastUpdate': 'آخر تحديث',
      'kb.markAsRead': 'تعليم كمقروء',
      'kb.markAsUnread': 'تعليم كغير مقروء',
      
      // FAQ
      'faq.title': 'الأسئلة الشائعة',
      'faq.subtitle': 'الأسئلة المتكررة والإجابات',
      'faq.search.placeholder': 'ابحث في الأسئلة',
      'faq.category': 'التصنيف',
      'faq.allCategories': 'جميع التصنيفات',
      'faq.noResults': 'لا توجد نتائج',
      'faq.noResultsDesc': 'لم نجد أي أسئلة تطابق بحثك. حاول استخدام كلمات مختلفة.',
      
      // Calculator
      'calc.title': 'الحاسبة المالية',
      'calc.description': 'احسب المؤشرات المالية الرئيسية بناءً على بيانات منظمتك',
      'calc.startCalculation': 'بدء الحساب',
      'calc.features.accurate': 'حسابات دقيقة',
      'calc.features.accurateDesc': 'نتائج مبنية على معايير محاسبية معتمدة',
      'calc.features.fast': 'سهل وسريع',
      'calc.features.fastDesc': 'احصل على نتائج فورية في دقائق',
      
      // Common
      'common.back': 'رجوع',
      'common.save': 'حفظ',
      'common.cancel': 'إلغاء',
      'common.view': 'عرض',
      'common.search': 'بحث',
      'common.filter': 'فلترة',
      'common.loading': 'جاري التحميل...',
      'common.noData': 'لا توجد بيانات',
      'common.switchToAdmin': 'التبديل إلى واجهة المسؤول',
    },
    en: {
      // Header
      'app.title': 'Knowledge Base',
      'header.welcome': 'Welcome',
      'header.entityName': 'Government Entity - Riyadh',
      
      // Navigation
      'nav.knowledgeBase': 'Knowledge Base',
      'nav.calculator': 'Financial Calculator',
      'nav.profile': 'Profile',
      'nav.notifications': 'Notifications',
      'nav.settings': 'Settings',
      
      // Knowledge Base
      'kb.title': 'Knowledge Base',
      'kb.subtitle': 'Browse available content and resources',
      'kb.tabs.available': 'Available Content',
      'kb.tabs.faq': 'FAQs',
      'kb.tabs.favorites': 'Favorites',
      'kb.subTabs.content': 'Content',
      'kb.subTabs.faq': 'FAQs',
      'kb.search.placeholder': 'Search content',
      'kb.filter.contentType': 'Content Type',
      'kb.filter.all': 'All',
      'kb.filter.guide': 'Guide',
      'kb.filter.assessment': 'Assessment',
      'kb.noFavorites': 'No favorite content',
      'kb.noFavoritesDesc': 'You haven\'t added any content to favorites yet. Start browsing available content and add what interests you.',
      'kb.browseContent': 'Browse Available Content',
      'kb.view': 'View',
      'kb.publishDate': 'Publish Date',
      'kb.lastUpdate': 'Last Updated',
      'kb.markAsRead': 'Mark as Read',
      'kb.markAsUnread': 'Mark as Unread',
      
      // FAQ
      'faq.title': 'Frequently Asked Questions',
      'faq.subtitle': 'Common questions and answers',
      'faq.search.placeholder': 'Search questions',
      'faq.category': 'Category',
      'faq.allCategories': 'All Categories',
      'faq.noResults': 'No results found',
      'faq.noResultsDesc': 'We couldn\'t find any questions matching your search. Try using different keywords.',
      
      // Calculator
      'calc.title': 'Financial Calculator',
      'calc.description': 'Calculate key financial indicators based on your organization\'s data',
      'calc.startCalculation': 'Start Calculation',
      'calc.features.accurate': 'Accurate Calculations',
      'calc.features.accurateDesc': 'Results based on approved accounting standards',
      'calc.features.fast': 'Easy and Fast',
      'calc.features.fastDesc': 'Get instant results in minutes',
      
      // Common
      'common.back': 'Back',
      'common.save': 'Save',
      'common.cancel': 'Cancel',
      'common.view': 'View',
      'common.search': 'Search',
      'common.filter': 'Filter',
      'common.loading': 'Loading...',
      'common.noData': 'No data available',
      'common.switchToAdmin': 'Switch to Admin View',
    }
  }
};

export function LanguageProvider({ children, module = 'admin' }: { children: ReactNode; module?: Module }) {
  const [language, setLanguage] = useState<Language>(module === 'admin' ? 'en' : 'ar');

  const t = (key: string): string => {
    return translations[module][language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, module, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}